title: Teemu Lamminmäki - SOC Specialist Student
theme: jekyll-theme-hacker
description: [Home](https://tmolam.github.io/)
[Certifications and Training](https://tmolam.github.io/Certifications-Training/)
[Tools and Projects](https://tmolam.github.io/Tools-Projects/)

